# Generated by Django 4.1.2 on 2022-11-02 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('nit', models.IntegerField()),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nuevoListado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
                ('precioCompra', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('creacion', models.DateField(auto_now_add=True)),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.compra')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipoprenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnidad', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
                ('producto', models.ManyToManyField(to='home.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sastreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('medidas', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('anticipo', models.IntegerField()),
                ('pendiente', models.IntegerField()),
                ('realizado', models.CharField(max_length=2)),
                ('entregado', models.CharField(max_length=2)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('tipoPrenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoprenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proveedor'),
        ),
        migrations.CreateModel(
            name='prendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('medidas', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('anticipo', models.IntegerField()),
                ('pendiente', models.IntegerField()),
                ('realizado', models.CharField(max_length=2)),
                ('entregado', models.CharField(max_length=2)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('listado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nuevolistado')),
                ('tipoPrenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoprenda')),
            ],
        ),
    ]
