# Generated by Django 4.1.2 on 2022-11-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Compra',
            new_name='compra',
        ),
    ]
